### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [OTR-Speed-Calculator/android#2]
There are 3 releases, but `versionCode` is still set to `1` with the latest one. Android uses `versionCode` to tell versions apart (and decide which APK is an update to the installed version). So could you please increase it just before you make a new release? Thanks a lot!

PS: Some screenshots would be nice to have, too :wink:

**Comment by ReduxFlakes** [comment]
I will release version 2.0 and I'll be sure to increase the `versionCode` and add screenshots! 👌

**Comment by ReduxFlakes** [comment]
The issues have been fixed! Source code updated and a compiled binary have been pushed with the fixes.
The screenshots can be found [in here](https://github.com/OTR-Speed-Calculator/android/tree/main/assets/screenshots) and on the README.md.
Thanks

**Comment by IzzySoft** [comment]
Now that was fast – thanks a lot! You've been faster than my scheduler: with the next sync around 6 pm UTC, your app becomes [available here](https://apt.izzysoft.de/fdroid/index/apk/net.tiago.otrsc) as a user requested it. I've added a few more screenshots there (just ran the app on my test device, so I also could set up a more detailed description).

Speaking of the latter: if you want, I can send you the metadata I've set up (description, screenshots etc) as [fastlane structures](https://gitlab.com/-/snippets/1895688) via PR. This would enable you to adjust them as you see fit – and my updater would pull changes along with the APK updates within 24h of your making a new release and have the APK attached.

**Comment by ReduxFlakes** [comment]
That would be awesome!

**Comment by ReduxFlakes** [comment]
That would be awesome!

**Comment by IzzySoft** [comment]
There you go :smiley:
